function [embryos, tool, motionLog] = moveToolToEmbryo( ...
    embryos, tool, numSteps, workspace, ...
    showIDs, showArrows, motionLog)

selectedID = 0;

for i = 1:length(embryos)
    if embryos(i).state == "selected"
        selectedID = i;
        break
    end
end

if selectedID == 0
    warning("No selected embryo found")
    return
end

targetPosition = embryos(selectedID).position ...
    + [0; 0; tool.clearance];

targetRotation = embryos(selectedID).orientation;

[embryos, tool, motionLog] = moveTool( ...
    embryos, ...
    tool, ...
    targetPosition, ...
    targetRotation, ...
    numSteps, ...
    workspace, ...
    showIDs, ...
    showArrows, ...
    motionLog);

tool.state = "aboveEmbryo";

end