function [embryos, tool, motionLog] = moveToolFinal( ...
    embryos, tool, movedPosition, workspace, ...
    showIDs, showArrows, motionLog)

attachedID = tool.attachedEmbryoID;

if attachedID == 0
    warning("Tool has no attached embryo")
    return
end

targetPosition = movedPosition + [0; 0; tool.clearance];

% Keep the current orientation while moving to the final position
targetRotation = tool.orientation;

[embryos, tool, motionLog] = moveTool( ...
    embryos, ...
    tool, ...
    targetPosition, ...
    targetRotation, ...
    25, ...
    workspace, ...
    showIDs, ...
    showArrows, ...
    motionLog);

tool.state = "aboveMovedPosition";

end