function [embryos, tool, motionLog] = raiseTool( ...
    embryos, tool, numSteps, workspace, ...
    showIDs, showArrows, motionLog)

targetPosition = tool.position + [0; 0; tool.clearance];

% Keep the current tool orientation while raising
targetRotation = tool.orientation;

[embryos, tool, motionLog] = moveTool( ...
    embryos, ...
    tool, ...
    targetPosition, ...
    targetRotation, ...
    numSteps, ...
    workspace, ...
    showIDs, ...
    showArrows, ...
    motionLog);

tool.state = "lifted";

end