function [embryos, tool, motionLog] = returnHome( ...
    embryos, tool, numSteps, workspace, ...
    showIDs, showArrows, motionLog)

targetPosition = tool.homePosition;

% Rotate back to the home orientation
targetRotation = eye(3);

[embryos, tool, motionLog] = moveTool( ...
    embryos, ...
    tool, ...
    targetPosition, ...
    targetRotation, ...
    numSteps, ...
    workspace, ...
    showIDs, ...
    showArrows, ...
    motionLog);

tool.state = "home";

end